### ISSUE TITLE
.news

### ISSUE THREAD

**Issue by mhf-ir** [likexian/whois-go#10]
try bbc.news:
error:
```
dial tcp: lookup news.whois-servers.net: no such host
```

I think must be whois.nic.news 
https://www.iana.org/domains/root/db/news.html

**Comment by likexian** [comment]
Hello @mhf-ir 
Thanks for feedback, I will fix it.

**Comment by likexian** [comment]
Hello @mhf-ir
This has been fixed, please try the latest version.

---
*If you think this repository is helpful, please share it with friends, thanks.*
