### ISSUE TITLE
cannot lookup .taxi domains

### ISSUE THREAD

**Issue by yasharne** [likexian/whois-go#11]
I'm trying to get whois info for `snapp.taxi` but I get this error: 

```dial tcp: lookup taxi.whois-servers.net: no such host```

**Comment by likexian** [comment]
Thanks for your feedback, I will fix it soon.

**Comment by likexian** [comment]
Hello @yasharne 
This has been fixed, please try the latest version.

---
*If you think this repository is helpful, please share it with friends, thanks.*
