### ISSUE TITLE
Cant "go get whois-go"

### ISSUE THREAD

**Issue by RomaLash** [likexian/whois-go#7]
Hello. 
After ur last update there is the problem.

if i try install like "go get -u github.com/likexian/whois-go", i ll get this one
"github.com/likexian/whois-go@v1.0.1: unknown revision v1.0.1"

Unfortunately, getting doesnt work neither by Docker, not by hands.

Thanks for ur attention

**Comment by likexian** [comment]
remove the line of whois-go in go.mod, and try to go get -u agagin.
if need help, please reopen a issue.

**Comment by RomaLash** [comment]
it helps, thank you
